services:
  - type: web
    name: donation-site
    env: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
